export default {
  width: 800,
  height: 600,
  invadersSpaceBetween: 6,
  invadersSpaceOutsideSwarm: 48,
  invadersLCount: 22,
  invadersLRows: 2,
  invadersMCount: 22,
  invadersMRows: 2,
  invadersSCount: 33,
  invadersSRows: 3,
  invadersSpeed: 50,
  invaderSScore: 10,
  invaderMScore: 15,
  invaderLScore: 20,
  laserSpeed: 300,
  invadersFallSpeed: 5,
  invadersShotMinInterval: 2,
  invadersShotMaxInterval: 5,
  invadersRunMinInterval: 5,
  invadersRunMaxInterval: 20,
};
